document.getElementById('sectionsA').innerHTML=`<section id="desk1"><div class="section-kicker">Desk 01 · Defining the right sources</div><div class="section-head"><h3>Start with the requirement, not the feed.</h3><p>Collection is part of the CTI lifecycle and must link directly to objectives. Internal sources show what happened inside your environment; external sources expand your view to threats seen elsewhere. TIPs and SIEMs aggregate both, but the source mix still needs deliberate selection.</p></div>
<div class="source-ledger">
<div class="source-row"><button><span class="kind">Internal</span><span class="name">Network logs</span><span class="why">Firewall, IDS/IPS, proxy and traffic activity</span><span class="plus">+</span><span class="source-detail">Useful for reconstructing observed activity and validating whether external indicators actually touched the organisation. Strong local relevance, but by itself it is reactive and cannot reveal threats never seen internally.</span></button></div>
<div class="source-row"><button><span class="kind">Internal</span><span class="name">User logs</span><span class="why">Authentication, access and behavioural history</span><span class="plus">+</span><span class="source-detail">Useful for suspicious access and compromised accounts. It gives local depth but limited global visibility.</span></button></div>
<div class="source-row"><button><span class="kind">Internal</span><span class="name">Application & server logs</span><span class="why">Business apps and server events</span><span class="plus">+</span><span class="source-detail">Application activity exposes exploit traces, failed requests, file access and attack paths. In the lecture’s XSS case, application logs identify the initial entry point.</span></button></div>
<div class="source-row"><button><span class="kind">Internal</span><span class="name">Malware analysis</span><span class="why">Samples captured in your environment</span><span class="plus">+</span><span class="source-detail">Extracts hashes, C2 infrastructure, file metadata and other IoCs shared with CTI, SOC and incident response teams.</span></button></div>
<div class="source-row"><button><span class="kind">External</span><span class="name">Government & law enforcement</span><span class="why">CISA, FBI, NCSC, NSA</span><span class="plus">+</span><span class="source-detail">Often trustworthy and useful for validated indicators, but many are based on already-observed incidents and still require local relevance checks.</span></button></div>
<div class="source-row"><button><span class="kind">External</span><span class="name">Communities & ISACs</span><span class="why">Sector sharing, peer reports, TTPs</span><span class="plus">+</span><span class="source-detail">Organisations with similar business profiles often face similar attackers. ISACs provide sector monitoring, sharing, exercises and incident support.</span></button></div>
<div class="source-row"><button><span class="kind">External</span><span class="name">Dark web & forums</span><span class="why">Early malware, exploit and actor chatter</span><span class="plus">+</span><span class="source-detail">Can reveal emerging exploits, malware and groups before surface-web reporting, but collection is noisy and must remain objective-led.</span></button></div>
<div class="source-row"><button><span class="kind">External</span><span class="name">Paid threat intelligence</span><span class="why">Curated or proprietary vendor intelligence</span><span class="plus">+</span><span class="source-detail">Can provide accuracy, timeliness, proprietary research and integration support, but cost, overlap and vendor trust must be managed.</span></button></div>
</div>
<div class="profile-builder" style="margin-top:18px"><div class="panel controls"><div class="label teal">Organisation intelligence profile</div><h4>Build Northstar Health’s collection profile</h4><label>CTI maturity<select id="maturity"><option>Level 1 — beginning</option><option>Level 2 — developing</option><option>Level 3 — mature</option></select></label><label>Monthly budget<select id="budgetLevel"><option>Low</option><option>Medium</option><option>High</option></select></label><label>Current platform<select id="platform"><option>SIEM only</option><option>TIP + SIEM</option><option>MITRE ATT&CK + TIP + SIEM</option></select></label><button id="profileBtn" style="padding:10px;background:var(--ink);color:#fff;border:0;font-weight:900">Generate source strategy</button></div><div class="recommend" id="recommend"><h4>Recommended mix</h4><ul><li>Start with internal logs + government/community OSINT.</li><li>Add healthcare ISAC sources for sector commonality.</li><li>Use STIX/TAXII-compatible feeds that your platform can ingest.</li><li>Trial commercial feeds only after measuring gaps and overlap.</li></ul><div class="scorebar"><span>Local relevance</span><i style="--v:92%"></i><b>92</b></div><div class="scorebar"><span>External breadth</span><i style="--v:72%"></i><b>72</b></div><div class="scorebar"><span>Cost efficiency</span><i style="--v:84%"></i><b>84</b></div></div></div>
<div class="three" style="margin-top:16px"><div class="panel"><div class="label orange">Feed evaluation</div><h4>Source · period · authentication</h4><p>Confirm the source type, check time relevance, and verify source transparency/authenticity.</p></div><div class="panel"><div class="label teal">Uniqueness</div><h4>Do not pay twice</h4><p>Measure overlap and unique data across candidate feeds. Multiple vendors may cover the same upstream source.</p></div><div class="panel"><div class="label lime">Quality</div><h4>Coverage · accuracy · latency · automation</h4><p>True/false positives, missed threats, delivery delay and automation determine operational usefulness.</p></div></div>
<div class="checkpoint" data-answer="1"><div class="q">Analyst check: a feed is highly reputable but 80% duplicates data you already ingest. What is the first concern?</div><button>Source authentication</button><button>Unique data / ROI</button><button>File size</button><div class="feedback"></div></div></section><section id="desk2"><div class="section-kicker">Desk 02 · Open Source Intelligence</div><div class="section-head"><h3>OSINT is cheap. Analyst time is not.</h3><p>OSINT is collective intelligence published openly: feeds, search engines, identities, domains, social platforms, malware portals and more. It gives level 1–2 programs a realistic starting point, but raw volume creates cleaning, validation and filtering work.</p></div>
<div class="exchange"><div class="market"><div class="market-head"><div>Source</div><div>Cost</div><div>Speed</div><div>Best for</div><div>Action</div></div>
<div class="market-row" data-cost="0"><b>CISA AIS</b><span>Free</span><span>Near-real</span><span>Indicators</span><button>Add</button></div>
<div class="market-row" data-cost="0"><b>AlienVault OTX</b><span>Free</span><span>Fast</span><span>Pulses / IoCs</span><button>Add</button></div>
<div class="market-row" data-cost="0"><b>Abuse.ch</b><span>Free</span><span>Fast</span><span>Malware / botnets</span><button>Add</button></div>
<div class="market-row" data-cost="0"><b>SANS ISC / DShield</b><span>Free</span><span>Fast</span><span>Internet attacks</span><button>Add</button></div>
<div class="market-row" data-cost="0"><b>VirusTotal</b><span>Free*</span><span>Fast</span><span>Malware analysis</span><button>Add</button></div>
<div class="market-row" data-cost="0"><b>Shodan / Censys</b><span>Free*</span><span>Fast</span><span>Exposure / ports</span><button>Add</button></div>
<div class="market-row" data-cost="350"><b>Healthcare ISAC</b><span>$350</span><span>Fast</span><span>Sector TTPs</span><button>Add</button></div>
<div class="market-row" data-cost="800"><b>Commercial curated feed</b><span>$800</span><span>Fast</span><span>Cleaned intel</span><button>Add</button></div></div>
<div class="panel dark"><div class="label lime">Feed marketplace</div><h4>Northstar trial budget</h4><div class="budget">$<span id="money">1,500</span> remaining</div><p>Select sources. Free feeds still consume analyst time; paid feeds consume budget. The aim is not to spend everything — it is to close the most important intelligence gaps.</p><div class="picklist" id="picklist"></div></div></div>
<div class="osint-map" style="margin-top:18px"><div class="osnode"><button><span class="num">01</span><h4>AIS</h4><p>STIX indicators over TAXII, near-real-time sharing and anonymised submissions.</p></button></div><div class="osnode"><button><span class="num">02</span><h4>OTX</h4><p>Community pulses, DirectConnect API, STIX/TAXII and MISP integration.</p></button></div><div class="osnode"><button><span class="num">03</span><h4>InfraGard / ISAC</h4><p>Law-enforcement and sector-specific sharing among common-profile organisations.</p></button></div><div class="osnode"><button><span class="num">04</span><h4>Abuse.ch</h4><p>MalwareBazaar, Feodo Tracker, URLhaus, ThreatFox and SSL intelligence.</p></button></div><div class="osnode"><button><span class="num">05</span><h4>Dark web</h4><p>Malware, exploits, zero-days, actor chatter and stolen credentials.</p></button></div><div class="osnode"><button><span class="num">06</span><h4>Shodan / Censys</h4><p>Internet-exposed devices, ports, protocols, services and certificates.</p></button></div><div class="osnode"><button><span class="num">07</span><h4>People / social / WiGLE</h4><p>Email exposure, identities, social platforms and wireless-network mapping.</p></button></div><div class="osnode"><button><span class="num">08</span><h4>VirusTotal / Any.Run</h4><p>Malware sandboxes, repositories, classification and IoCs.</p></button></div></div>
<div class="darkweb" style="margin-top:16px"><div class="label lime">Dark web watchroom · click “useful?”</div><div class="forum"><div class="post">“Selling access to AU healthcare portals through unpatched middleware.” <button data-useful="1">Useful?</button></div><div class="post">“New ransomware builder v5 — includes evasion against EDR.” <button data-useful="1">Useful?</button></div><div class="post">“100% undetectable hack tool!!! DM now!!!” <button data-useful="0">Useful?</button></div><div class="post">“Proof-of-concept exploit targeting the same server stack Northstar runs.” <button data-useful="1">Useful?</button></div></div></div>
<div class="two" style="margin-top:16px"><div class="panel"><h4>Benefits</h4><p>Low/no cost, public maintenance, API/download accessibility, constant availability and fast cross-border sharing.</p></div><div class="panel"><h4>Limitations</h4><p>Raw data needs cleaning, uncontrolled sources need validation, volume creates false positives, and automation still requires field expertise.</p></div></div>
<div class="checkpoint" data-answer="2"><div class="q">Analyst check: why should a CTI team cross-verify a security-news report before acting?</div><button>News is always late</button><button>Paid feeds prohibit it</button><button>OSINT can contain noise or misleading information</button><div class="feedback"></div></div></section>`;
